# This list of English stop words is taken from the "Glasgow Information
# Retrieval Group". The original list can be found at
# http://ir.dcs.gla.ac.uk/resources/linguistic_utils/stop_words
ENGLISH_STOP_WORDS = frozenset([
    "a", "about", "above", "across", "after", "afterwards", "again", "against",
    "all", "almost", "alone", "along", "already", "also", "although", "always",
    "am", "among", "amongst", "amoungst", "amount", "an", "and", "another",
    "any", "anyhow", "anyone", "anything", "anyway", "anywhere", "are",
    "around", "as", "at", "back", "be", "became", "because", "become",
    "becomes", "becoming", "been", "before", "beforehand", "behind", "being",
    "below", "beside", "besides", "between", "beyond", "bill", "both",
    "bottom", "but", "by", "call", "can", "cannot", "cant", "co", "con",
    "could", "couldnt", "cry", "de", "describe", "detail", "do", "done",
    "down", "due", "during", "each", "eg", "eight", "either", "eleven", "else",
    "elsewhere", "empty", "enough", "etc", "even", "ever", "every", "everyone",
    "everything", "everywhere", "except", "few", "fifteen", "fifty", "fill",
    "find", "fire", "first", "five", "for", "former", "formerly", "forty",
    "found", "four", "from", "front", "full", "further", "get", "give", "go",
    "had", "has", "hasnt", "have", "he", "hence", "her", "here", "hereafter",
    "hereby", "herein", "hereupon", "hers", "herself", "him", "himself", "his",
    "how", "however", "hundred", "i", "ie", "if", "in", "inc", "indeed",
    "interest", "into", "is", "it", "its", "itself", "keep", "last", "latter",
    "latterly", "least", "less", "ltd", "made", "many", "may", "me",
    "meanwhile", "might", "mill", "mine", "more", "moreover", "most", "mostly",
    "move", "much", "must", "my", "myself", "name", "namely", "neither",
    "never", "nevertheless", "next", "nine", "no", "nobody", "none", "noone",
    "nor", "not", "nothing", "now", "nowhere", "of", "off", "often", "on",
    "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our",
    "ours", "ourselves", "out", "over", "own", "part", "per", "perhaps",
    "please", "put", "rather", "re", "same", "see", "seem", "seemed",
    "seeming", "seems", "serious", "several", "she", "should", "show", "side",
    "since", "sincere", "six", "sixty", "so", "some", "somehow", "someone",
    "something", "sometime", "sometimes", "somewhere", "still", "such",
    "system", "take", "ten", "than", "that", "the", "their", "them",
    "themselves", "then", "thence", "there", "thereafter", "thereby",
    "therefore", "therein", "thereupon", "these", "they", "thick", "thin",
    "third", "this", "those", "though", "three", "through", "throughout",
    "thru", "thus", "to", "together", "too", "top", "toward", "towards",
    "twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us",
    "very", "via", "was", "we", "well", "were", "what", "whatever", "when",
    "whence", "whenever", "where", "whereafter", "whereas", "whereby",
    "wherein", "whereupon", "wherever", "whether", "which", "while", "whither",
    "who", "whoever", "whole", "whom", "whose", "why", "will", "with",
    "within", "without", "would", "yet", "you", "your", "yours", "yourself",
    "yourselves"])


#Leech, G., M. Deuchar and R. Hoogenraad (1982) English Grammar For Today. London: Macmillan. (Chapter 3)
ENGLISH_CLOSED_CLASS_WORDS = frozenset(['the','a','an','this','that','these','those','all',
    'some','any','no','every','each','either','neither','one','several','enough','such','many',
    'much','more','most','few','fewer','fewest','little','less','least','what','which','whatever',
    'whichever','half','I','me','my','mine','myself','we','us','ourselves','our','ours','you','yourself',
    'yourselves','your','yours','he','him','himself','his','she','her','herself','hers','it','itself','its',
    'they','them','themselves','their','theirs','this','that','these','those','all','some','any','none',
    'each','either','neither','one','oneself','several','everybody','everyone','everything',
    'somebody','someone','something','anybody','anyone','anything','nobody','nothing',
    'many','much','more','most','few','fewer','fewest','little','less','least','who','whom','whose',
    'what','which','whoever','whichever','whatever','about','above','across','after','against','along',
    'alongside','amid','among','around','as','at','before','behind','below','beneath','beside','besides',
    'between','beyond','by','despite','down','during','for','from','in','inside','into','of','off','on',
    'opposite','outside','over','past','round','since','than','through','throughout','till','to','towards',
    'toward','under','underneath','until','up','via','with','within','without','after','although','as',
    'because','before','but','if','how','however','like','once','since','than','that','till','unless','until',
    'when','whenever','wherever','wheras','whereby','whereupon','while','and','or','but','not',
    'neither','can','will','may','shall','could','would','might','should','must'])